apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-api-dev
  namespace: argocd
  annotations:
    argo.octopus.com/project: test
    argo.octopus.com/environment: development
spec:
  project: default
  source:
    repoURL: https://github.com/oleksandr-codefresh/finpay-deploy.git
    targetRevision: main
    path: argocd-manifests/payments-api/development
  destination:
    server: https://kubernetes.default.svc
    namespace: payments-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true